package jisa.devices.camera.nat;

import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;

public interface LucamError {

    int LucamNoError                       = 0;
    int LucamNoSuchIndex                   = 1;
    int LucamSnapshotNotSupported          = 2;
    int LucamInvalidPixelFormat            = 3;
    int LucamSubsamplingZero               = 4;
    int LucamBusy                          = 5;
    int LucamFailedToSetSubsampling        = 6;
    int LucamFailedToSetStartPosition      = 7;
    int LucamPixelFormatNotSupported       = 8;
    int LucamInvalidFrameFormat            = 9;
    int LucamPreparationFailed             = 10;
    int LucamCannotRun                     = 11;
    int LucamNoTriggerControl              = 12;
    int LucamNoPin                         = 13;
    int LucamNotRunning                    = 14;
    int LucamTriggerFailed                 = 15;
    int LucamCannotSetupFrameFormat        = 16;
    int LucamDirectShowInitError           = 17;
    int LucamCameraNotFound                = 18;
    int LucamTimeout                       = 19;
    int LucamPropertyUnknown               = 20;
    int LucamPropertyUnsupported           = 21;
    int LucamPropertyAccessFailed          = 22;
    int LucamLucustomNotFound              = 23;
    int LucamPreviewNotRunning             = 24;
    int LucamLutfNotLoaded                 = 25;
    int LucamDirectShowError               = 26;
    int LucamNoMoreCallbacks               = 27;
    int LucamUndeterminedFrameFormat       = 28;
    int LucamInvalidParameter              = 29;
    int LucamNotEnoughResources            = 30;
    int LucamNoSuchConversion              = 31;
    int LucamParameterNotWithinBoundaries  = 32;
    int LucamBadFileIo                     = 33;
    int LucamGdiplusNotFound               = 34;
    int LucamGdiplusError                  = 35;
    int LucamUnknownFormatType             = 36;
    int LucamFailedCreateDisplay           = 37;
    int LucamDpLibNotFound                 = 38;
    int LucamDpCmdNotSupported             = 39;
    int LucamDpCmdUnknown                  = 40;
    int LucamNotWhilePaused                = 41;
    int LucamCaptureFailed                 = 42;
    int LucamDpError                       = 43;
    int LucamNoSuchFrameRate               = 44;
    int LucamInvalidTarget                 = 45;
    int LucamFrameTooDark                  = 46;
    int LucamKsPropertySetNotFound         = 47;
    int LucamCancelled                     = 48;
    int LucamKsControlNotSupported         = 49;
    int LucamEventNotSupported             = 50;
    int LucamNoPreview                     = 51;
    int LucamSetPositionFailed             = 52;
    int LucamNoFrameRateList               = 53;
    int LucamFrameRateInconsistent         = 54;
    int LucamCameraNotConfiguredForCmd     = 55;
    int LucamGraphNotReady                 = 56;
    int LucamCallbackSetupError            = 57;
    int LucamInvalidTriggerMode            = 58;
    int LucamNotFound                      = 59;
    int LucamPermanentBufferNotSupported   = 60;
    int LucamEepromWriteFailed             = 61;
    int LucamUnknownFileType               = 62;
    int LucamEventIdNotSupported           = 63;
    int LucamEepromCorrupted               = 64;
    int LucamSectionTooBig                 = 65;
    int LucamFrameTooBright                = 66;
    int LucamNoCorrectionMatrix            = 67;
    int LucamUnknownCameraModel            = 68;
    int LucamApiTooOld                     = 69;
    int LucamSaturationZero                = 0;
    int LucamAlreadyInitialised            = 1;
    int LucamSameInputAndOutputFile        = 2;
    int LucamFileConversionFailed          = 3;
    int LucamFileAlreadyConverted          = 4;
    int LucamPropertyPageNotSupported      = 75;
    int LucamPropertyPageCreationFailed    = 76;
    int LucamDirectShowFilterNotInstalled  = 77;
    int LucamIndividualLutNotAvailable     = 78;
    int LucamUnexpectedError               = 79;
    int LucamStreamingStopped              = 80;
    int LucamMustBeInSwTriggerMode         = 81;
    int LucamTargetFlaky                   = 82;
    int LucamAutoLensUninitialized         = 83;
    int LucamLensNotInstalled              = 84;
    int LucamUnknownError                  = 85;
    int LucamFocusNoFeedbackError          = 86;
    int LucamLutfTooOld                    = 87;
    int LucamUnknownAviFormat              = 88;
    int LucamUnknownAviType                = 89;
    int LucamInvalidAviConversion          = 90;
    int LucamSeekFailed                    = 91;
    int LucamAviRunning                    = 92;
    int LucamCameraAlreadyOpened           = 93;
    int LucamNoSubsampledHighRes           = 94;
    int LucamOnlyOnMonochrome              = 95;
    int LucamNo8bppTo48bpp                 = 96;
    int LucamLut8Obsolete                  = 97;
    int LucamFunctionNotSupported          = 98;
    int LucamRetryLimitReached             = 99;
    int LucamLgDeviceError                 = 100;
    int LucamInvalidIpConfiguration        = 101;
    int LucamInvalidLicense                = 102;
    int LucamNoSystemEnumerator            = 103;
    int LucamBusEnumeratorNotInstalled     = 104;
    int LucamUnknownExternInterface        = 105;
    int LucamInterfaceDriverNotInstalled   = 106;
    int LucamCameraDriverNotInstalled      = 107;
    int LucamCameraDriverInstallInProgress = 108;
    int LucamLucamapiDotDllNotFound        = 109;
    int LucamLucamapiProcedureNotFound     = 110;
    int LucamPropertyNotEnumeratable       = 111;
    int LucamPropertyNotBufferable         = 112;
    int LucamSingleTapImage                = 113;
    int LucamUnknownTapConfiguration       = 114;
    int LucamBufferTooSmall                = 115;
    int LucamInCallbackOnly                = 116;
    int LucamPropertyUnavailable           = 117;
    int LucamTimestampNotEnabled           = 118;
    int LucamFramecounterNotEnabled        = 119;
    int LucamNoStatsWhenNotStreaming       = 120;
    int LucamFrameCapturePending           = 121;
    int LucamSequencingNotEnabled          = 122;
    int LucamFeatureNotSequencable         = 123;
    int LucamSequencingUnknownFeatureType  = 124;
    int LucamSequencingIndexOutOfSequence  = 125;
    int LucamSequencingBadFrameNumber      = 126;
    int LucamInformationNotAvailable       = 127;
    int LucamSequencingBadSetting          = 128;
    int LucamAutoFocusNeverStarted         = 129;
    int LucamAutoFocusNotRunning           = 130;
    int LucamCameraNotOpenable             = 1121;
    int LucamCameraNotSupported            = 1122;
    int LucamMmapFailed                    = 1123;
    int LucamNotWhileStreaming             = 1124;
    int LucamNoStreamingRights             = 1125;
    int LucamCameraInitializationError     = 1126;
    int LucamCannotVerifyPixelFormat       = 1127;
    int LucamCannotVerifyStartPosition     = 1128;
    int LucamOsError                       = 1129;
    int LucamBufferNotAvailable            = 1130;
    int LucamQueuingFailed                 = 1131;

    Map<Integer, String> NAMES = Arrays.stream(LucamError.class.getDeclaredFields())
                                       .filter(f -> Integer.class.isAssignableFrom(f.getType())).map(f -> {
                                           try {
                                               return Map.entry(f.getName(), (int) f.get(null));
                                           } catch (IllegalAccessException e) {
                                               return null;
                                           }
                                       }).filter(e -> e != null)
                                       .collect(Collectors.toMap(Map.Entry::getValue, Map.Entry::getKey));

}
