package JISA.VISA;

import com.sun.jna.*;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.NativeLongByReference;
import com.sun.jna.ptr.ShortByReference;

import java.nio.IntBuffer;
import java.nio.ShortBuffer;

/**
 * JNA Wrapper for library <b>NI4882</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface GPIBNativeInterface extends Library {

    int                   T1000s            = 17;
    int                   IbcAUTOPOLL       = 7;
    int                   EADR              = 3;
    int                   IbaHSCableLength  = 31;
    int                   IbaBNA            = 512;
    int                   SDC               = 4;
    int                   ECIC              = 1;
    short                 ValidNRFD         = (short) 4;
    int                   IbaSerialNumber   = 35;
    int                   IbaREADDR         = 6;
    int                   IbcSC             = 10;
    int                   NLend             = 1;
    short                 BusSRQ            = (short) 8192;
    short                 ValidATN          = (short) 64;
    short                 ValidREN          = (short) 16;
    int                   T100s             = 15;
    int                   PPC               = 5;
    int                   PPE               = 96;
    int                   IbcEOT            = 4;
    int                   PPD               = 112;
    int                   IbcTMO            = 3;
    short                 ValidIFC          = (short) 8;
    int                   IbaSAD            = 2;
    int                   EHDL              = 23;
    int                   EDMA              = 8;
    int                   PPU               = 21;
    int                   IbaSRE            = 11;
    int                   T100us            = 3;
    short                 BusDAV            = (short) 256;
    int                   IbaEndBitIsNormal = 26;
    int                   T3ms              = 6;
    int                   ENOL              = 2;
    int                   IbcDMA            = 18;
    int                   IbaSendLLO        = 23;
    int                   NULLend           = 0;
    int                   IbcEOScmp         = 14;
    int                   REM               = 1 << 6;
    int                   ATN               = 1 << 4;
    int                   IbcEOS            = 37;
    int                   IbcLON            = 34;
    int                   LACS              = 1 << 2;
    int                   IbaEOSwrt         = 13;
    int                   SRQI              = 1 << 12;
    int                   IbcHSCableLength  = 31;
    int                   IbaSPollTime      = 24;
    short                 BusNRFD           = (short) 1024;
    int                   CIC               = 1 << 5;
    int                   EFSO              = 12;
    short                 ValidEOI          = (short) 128;
    int                   WCFG              = 24;
    int                   IbaSC             = 10;
    int                   T30us             = 2;
    int                   T300ms            = 10;
    int                   END               = 1 << 13;
    int                   IbaUnAddr         = 27;
    int                   T30s              = 14;
    int                   IbcEOSwrt         = 13;
    int                   IbaRsv            = 33;
    int                   LLO               = 17;
    int                   IbaPP2            = 16;
    int                   UNL               = 63;
    int                   UNT               = 95;
    int                   IbaPPC            = 5;
    int                   IbcEOSchar        = 15;
    int                   IbaTIMING         = 17;
    int                   DTAS              = 1 << 1;
    int                   T1ms              = 5;
    int                   EPWR              = 28;
    int                   BIN               = 1 << 12;
    int                   IbcEOSrd          = 12;
    int                   DABend            = 2;
    int                   IbcUnAddr         = 27;
    int                   DCAS              = 1 << 0;
    int                   IbcSendLLO        = 23;
    int                   T10ms             = 7;
    int                   TIMO              = 1 << 14;
    int                   GTL               = 1;
    int                   IbaIst            = 32;
    int                   T300s             = 16;
    int                   IbcPPollTime      = 25;
    int                   IbcSAD            = 2;
    int                   IbaPAD            = 1;
    int                   IbcSRE            = 11;
    short                 BusIFC            = (short) 2048;
    int                   ENEB              = 7;
    int                   LOK               = 1 << 7;
    int                   IbcTIMING         = 17;
    int                   ETAB              = 20;
    int                   GET               = 8;
    int                   IbaEOScmp         = 14;
    short                 BusEOI            = (short) 32768;
    short                 ValidDAV          = (short) 1;
    int                   T300us            = 4;
    int                   IbaEOSrd          = 12;
    int                   ERR               = 1 << 15;
    int                   T10s              = 13;
    int                   TNONE             = 0;
    int                   ESRQ              = 16;
    int                   IbcEndBitIsNormal = 26;
    int                   IbaPPollTime      = 25;
    short                 ValidSRQ          = (short) 32;
    short                 BusREN            = (short) 4096;
    short                 BusATN            = (short) 16384;
    int                   IbaEOSchar        = 15;
    int                   ECAP              = 11;
    int                   ELCK              = 21;
    int                   ESAC              = 5;
    int                   EOIP              = 10;
    int                   REOS              = 1 << 10;
    short                 ValidNDAC         = (short) 2;
    int                   ALL_SAD           = -1;
    int                   EWIP              = 26;
    int                   IbaAUTOPOLL       = 7;
    int                   IbaEOT            = 4;
    int                   IbaEOS            = 37;
    int                   SPD               = 25;
    int                   SPE               = 24;
    int                   IbaTMO            = 3;
    int                   IbcPP2            = 16;
    int                   IbcRsv            = 33;
    int                   IbcPPC            = 5;
    int                   T30ms             = 8;
    int                   T100ms            = 9;
    int                   NO_SAD            = 0;
    int                   DCL               = 20;
    int                   IbaDMA            = 18;
    int                   T1s               = 11;
    int                   XEOS              = 1 << 11;
    int                   TACS              = 1 << 3;
    int                   EDVR              = 0;
    int                   ESTB              = 15;
    short                 BusNDAC           = (short) 512;
    int                   TCT               = 9;
    int                   IbcIst            = 32;
    int                   IbaLON            = 34;
    int                   EABO              = 6;
    int                   IbcPAD            = 1;
    int                   EBUS              = 14;
    int                   STOPend           = 256;
    int                   T10us             = 1;
    int                   ERST              = 27;
    int                   EARG              = 4;
    int                   RQS               = 1 << 11;
    int                   T3s               = 12;
    int                   IbcREADDR         = 6;
    int                   EARM              = 22;
    int                   IbcSPollTime      = 24;
    int                   CMPL              = 1 << 8;
    int                   ECFG              = 24;
    IntByReference        ibsta             = new IntByReference();
    IntByReference        iberr             = new IntByReference();
    IntByReference        ibcnt             = new IntByReference();
    NativeLongByReference ibcntl            = new NativeLongByReference();

    @Deprecated
    int ibfindA(Pointer udname);

    int ibfindA(String udname);

    @Deprecated
    int ibrdfA(int ud, Pointer filename);

    int ibrdfA(int ud, String filename);

    @Deprecated
    int ibwrtfA(int ud, Pointer filename);

    int ibwrtfA(int ud, String filename);

    int ibfindW(WString udname);

    int ibrdfW(int ud, WString filename);

    int ibwrtfW(int ud, WString filename);

    @Deprecated
    int ibask(int ud, int option, IntByReference v);

    int ibask(int ud, int option, IntBuffer v);

    int ibcac(int ud, int v);

    int ibclr(int ud);

    int ibcmd(int ud, Pointer buf, int cnt);

    int ibcmda(int ud, Pointer buf, int cnt);

    int ibconfig(int ud, int option, int v);

    int ibdev(int boardID, int pad, int sad, int tmo, int eot, int eos);

    int ibexpert(int ud, int option, Pointer Input, Pointer Output);

    int ibgts(int ud, int v);

    int iblck(int ud, int v, int LockWaitTime, Pointer Reserved);

    @Deprecated
    int iblines(int ud, ShortByReference result);

    int iblines(int ud, ShortBuffer result);

    @Deprecated
    int ibln(int ud, int pad, int sad, ShortByReference listen);

    int ibln(int ud, int pad, int sad, ShortBuffer listen);

    int ibloc(int ud);

    int ibnotify(int ud, int mask, Callback Callback, Pointer RefData);

    int ibonl(int ud, int v);

    int ibpct(int ud);

    int ibppc(int ud, int v);

    int ibrd(int ud, Pointer buf, int cnt);

    int ibrda(int ud, Pointer buf, int cnt);

    @Deprecated
    int ibrpp(int ud, Pointer ppr);

    int ibrpp(int ud, String ppr);

    @Deprecated
    int ibrsp(int ud, Pointer spr);

    int ibrsp(int ud, String spr);

    int ibsic(int ud);

    int ibstop(int ud);

    int ibtrg(int ud);

    int ibwait(int ud, int mask);

    int ibwrt(int ud, Pointer buf, int cnt);

    int ibwrta(int ud, Pointer buf, int cnt);

    @Deprecated
    void AllSpoll(int boardID, ShortByReference addrlist, ShortByReference results);

    void AllSpoll(int boardID, short[] addrlist, ShortBuffer results);

    void DevClear(int boardID, short addr);

    @Deprecated
    void DevClearList(int boardID, ShortByReference addrlist);

    void DevClearList(int boardID, short[] addrlist);

    @Deprecated
    void EnableLocal(int boardID, ShortByReference addrlist);

    void EnableLocal(int boardID, short[] addrlist);

    @Deprecated
    void EnableRemote(int boardID, ShortByReference addrlist);

    void EnableRemote(int boardID, short[] addrlist);

    @Deprecated
    void FindLstn(int boardID, ShortByReference addrlist, ShortByReference results, int limit);

    void FindLstn(int boardID, short[] addrlist, ShortBuffer results, int limit);

    @Deprecated
    void FindRQS(int boardID, ShortByReference addrlist, ShortByReference dev_stat);

    void FindRQS(int boardID, short[] addrlist, ShortBuffer dev_stat);

    @Deprecated
    void PPoll(int boardID, ShortByReference result);

    void PPoll(int boardID, ShortBuffer result);

    void PPollConfig(int boardID, short addr, int dataLine, int lineSense);

    @Deprecated
    void PPollUnconfig(int boardID, ShortByReference addrlist);

    void PPollUnconfig(int boardID, short[] addrlist);

    void PassControl(int boardID, short addr);

    void RcvRespMsg(int boardID, Pointer buffer, int cnt, int Termination);

    @Deprecated
    void ReadStatusByte(int boardID, short addr, ShortByReference result);

    void ReadStatusByte(int boardID, short addr, ShortBuffer result);

    void Receive(int boardID, short addr, Pointer buffer, int cnt, int Termination);

    void ReceiveSetup(int boardID, short addr);

    @Deprecated
    void ResetSys(int boardID, ShortByReference addrlist);

    void ResetSys(int boardID, short[] addrlist);

    void Send(int boardID, short addr, Pointer databuf, int datacnt, int eotMode);

    void SendCmds(int boardID, Pointer buffer, int cnt);

    void SendDataBytes(int boardID, Pointer buffer, int cnt, int eot_mode);

    void SendIFC(int boardID);

    void SendLLO(int boardID);

    @Deprecated
    void SendList(int boardID, ShortByReference addrlist, Pointer databuf, int datacnt, int eotMode);

    void SendList(int boardID, short[] addrlist, Pointer databuf, int datacnt, int eotMode);

    @Deprecated
    void SendSetup(int boardID, ShortByReference addrlist);

    void SendSetup(int boardID, short[] addrlist);

    @Deprecated
    void SetRWLS(int boardID, ShortByReference addrlist);

    void SetRWLS(int boardID, short[] addrlist);

    @Deprecated
    void TestSRQ(int boardID, ShortByReference result);

    void TestSRQ(int boardID, ShortBuffer result);

    @Deprecated
    void TestSys(int boardID, ShortByReference addrlist, ShortByReference results);

    void TestSys(int boardID, short[] addrlist, ShortBuffer results);

    void Trigger(int boardID, short addr);

    @Deprecated
    void TriggerList(int boardID, ShortByReference addrlist);

    void TriggerList(int boardID, short[] addrlist);

    @Deprecated
    void WaitSRQ(int boardID, ShortByReference result);

    void WaitSRQ(int boardID, ShortBuffer result);
}
