package jisa.devices.camera.feature;

import jisa.devices.DeviceException;
import jisa.devices.ParameterList;
import jisa.devices.features.Feature;

import java.io.IOException;

public interface Timestamping extends Feature {

    static void addParameters(Timestamping inst, Class<?> target, ParameterList parameters) {
        parameters.addValue("Hardware Timestamping", inst::isTimestampEnabled, false, inst::setTimestampEnabled);
    }

    /**
     * Returns whether the timestamp on each frame is generated by the camera itself. If not, the current computer time
     * will be used instead (less accurate).
     *
     * @return Is the camera timestamping?
     *
     * @throws IOException     Upon communications error
     * @throws DeviceException Upon device compatibility error
     */
    boolean isTimestampEnabled() throws IOException, DeviceException;

    /**
     * Sets whether the timestamp on each frame is generated by the camera itself. If not, the current computer time
     * will be used instead (less accurate).
     *
     * @param timestamping Should the camera do the timestamping?
     *
     * @throws IOException     Upon communications error
     * @throws DeviceException Upon device compatibility error
     */
    void setTimestampEnabled(boolean timestamping) throws IOException, DeviceException;

}
